### ISSUE TITLE
Print-friendly button not working

### ISSUE THREAD

**Issue by capsulecorplab** [DocOps/asciidocsy-jekyll-theme#54] opened 2021-07-08 00:46 UTC
Clicking the "Print-friendly" button causes the navbar to disappear for about a half second, but then reappears.

**Comment by briandominick** [comment] 2021-07-09 00:48
Duplicate of #4 so I'm going to close this.

I intend to fix this for 0.2.0 release coming out asap. Thanks for letting me know!

**Closed by briandominick** 2021-07-09 00:48 UTC
Labels: duplicate
